config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get '/history', to: 'home#history'
  get '/log',     to: 'home#log'
  match '/log_create' => 'home#log_create', :via => :post, :as => 'log_create'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :player1, class_name:'User'
  belongs_to :player2, class_name:'User'
  validates :player1, presence: true
  validates :player2, presence: true
  validates :player1_score, :numericality => { :less_than_or_equal_to => 21 }, :presence => true
  validates :player2_score, :numericality => { :less_than_or_equal_to => 21 }, :presence => true
  validate :same_players


  after_save :update_scores

  require 'elo'


  def same_players
    if self.player1_id == self.player2_id
    errors.add(:player1, "You cant play with yourself")
    end
  end

  def update_scores
    player1_elo_score = RatedPlayer.new("Player1",self.player1.score)
    player2_elo_score = RatedPlayer.new("Player2",self.player2.score)
    elo_type = 0.5
    if player1_score - 1 > player2_score
      elo_type = 1
    elsif player1_score < player2_score - 1
      elo_type = 0
    end
    Match.new(player1_elo_score,player2_elo_score,elo_type)

    self.player1.update_attribute(:score,player1_elo_score.rating)
    self.player2.update_attribute(:score,player2_elo_score.rating)
  end

  def user_result(user)
    user_score = get_score_user(user)
    opponent_score = get_score_opponent(user)
    result = 'D'
    if user_score - 1 > opponent_score
      result = 'W'
    elsif user_score < opponent_score - 1
      result = 'L'
    end
    result
  end

  def get_score_user(user)
    if player1.id == user.id
      player1_score
    elsif player2.id == user.id
      player2_score
    else
      0
    end
  end

  def get_score_opponent(user)
    if player1.id == user.id
      player2_score
    elsif player2.id == user.id
      player1_score
    else
      0
    end
  end

  def get_opponent(user)
    if player1.id == user.id
      player2
    elsif player2.id == user.id
      player1
    else
      User.new
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable

  scope :opponents, ->(user) { where('id!=?' ,user.id) }
  scope :forboard, -> { order(score: :desc) }
  def games
    Game.where('player1_id =? OR player2_id =?',self.id,self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @notice = params[:notice]
    @users = User.all.forboard
  end

  def history
    @notice = params[:notice]
    @games = current_user.games
  end

  def log
    @game = Game.new
  end

  def log_create
    @game = Game.new(game_params)
    @game.player1 = current_user
    if @game.valid?
      @game.save
      redirect_to history_path notice:'Game saved'
    else
      @notice = @game.errors
      render :log
    end
  end

  def game_params
    params.require(:game).permit(:date_played,:player2_id,:player1_score,:player2_score)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<% if @notice %>
    <div class="alert alert-warning" role="alert"><%= @notice =%></div>
<% end %>


<table class="table">
  <thead>
  <th>Date</th>
  <th>Opponent</th>
  <th>Score</th>
  <th>Result</th>
  </thead>
  <tbody>
  <% @games.each do |game| %>
      <tr>
        <td><%= game.date_played %></td>
        <td><%= game.get_opponent(current_user).try(:email) %></td>
        <td><%= "#{game.get_score_user(current_user)} -#{game.get_score_opponent(current_user)}"%></td>
        <td><%= game.user_result(current_user) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>


<% if @notice %>
    <div class="alert alert-warning" role="alert"><%= @notice =%></div>
<% end %>


<table class="table">
  <thead>
  <th>Rank</th>
  <th>Name</th>
  <th>Score</th>
  <th>Games played</th>
  </thead>
  <tbody>
  <% @users.each_with_index do |user,index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= user.email %></td>
        <td><%= user.score%></td>
        <td><%= user.games.count %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>
<% if @notice %>
    <div class="alert alert-warning" role="alert">
      <% @notice.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </div>
<% end %>
<%= form_for @game ,:url=> log_create_path do |f| %>
    <div class="form-group">
      <label>Date played</label>
      <%= f.datetime_select :date_played ,class:"form-control"%>
    </div>
    <div class="form-group">
      <label>Opponent</label>
    <%= f.select :player2_id,  options_from_collection_for_select(User.opponents(current_user), "id", "email"),class:"form-control"%>
    </div>
    <div class="form-group">
      <label>Your Score</label>
      <%= f.text_field  :player1_score ,class:"form-control"%>
    </div>
    <div class="form-group">
      <label>Their Score</label>
      <%= f.text_field  :player2_score ,class:"form-control"%>
    </div>
    <%= f.submit %>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>